name: trippify

services:
  mongodb:
    image: mongo:latest
    command: --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db:rw

  backend:
    build:
      context: ./backend
      target: hot-reload
    command: -build="sleep 3 && go build -o /build main.go" -command="/build/main" -log-prefix=false
    volumes:
      - ./backend:/app:ro
    depends_on:
      - mongodb
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./frontend
    command: dev:network

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  #  certbot:
  #    image: certbot/certbot
  #    volumes:
  #      - /etc/letsencrypt:/etc/letsencrypt
  #      - /var/log/letsencrypt:/var/log/letsencrypt

volumes:
  mongodb-data: